// Index de la recherche du site (components/recherche-site.tsx).
// Titres et descriptions repris des pages (titre principal et meta description) ; « motsCles »
// ajoute les synonymes que les visiteurs tapent (cariste, PEMP, TMS…).
// Nouvelle page ? Ajoutez-y une ligne, sinon elle n'apparaîtra pas dans la recherche.

export type PageRecherche = {
  href: string;
  titre: string;
  description: string;
  categorie: "Formation" | "VGP" | "Outil" | "SECURIFORM" | "Informations";
  motsCles: string;
};

export const PAGES_RECHERCHE: PageRecherche[] = [
  {"href":"/","titre":"Accueil","description":"SECURIFORM, organisme de formation certifié Qualiopi : habilitation électrique, CACES®, SST, incendie, travaux en hauteur, AIPR, VGP, sur toute la moitié nord de la France.","categorie":"SECURIFORM","motsCles":"accueil securiform"},
  {"href":"/caces","titre":"Formations à la conduite en sécurité et CACES®","description":"SECURIFORM prépare vos équipes au CACES® : R482B, R484A, R485A, R486B, R489A et R490A. Tests réalisés par un organisme testeur certifié INRS, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"caces conduite engins permis"},
  {"href":"/habilitation-electrique","titre":"Préparation à l'habilitation électrique","description":"SECURIFORM prépare à l'habilitation électrique le personnel électricien et non-électricien, basse et haute tension, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"electricite electrique habilitation NF C18-510 B0 H0 BS BE BR B1 B2"},
  {"href":"/secourisme","titre":"Formation secourisme (SST)","description":"SECURIFORM est centre habilité SST : formation initiale de 14h et MAC de recyclage tous les 24 mois, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"SST secourisme premiers secours sauveteur secouriste"},
  {"href":"/incendie-evacuation","titre":"Formations incendie et évacuation","description":"SECURIFORM forme à la manipulation des extincteurs et RIA, à l'évacuation des locaux et aux Équipiers de Première Intervention.","categorie":"Formation","motsCles":"incendie feu extincteur evacuation"},
  {"href":"/travaux-hauteur-echafaudages","titre":"Formations travaux en hauteur et échafaudages","description":"SECURIFORM forme au port du harnais anti-chute et au montage d'échafaudages fixes (R408) et roulants (R457), sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"hauteur harnais echafaudage"},
  {"href":"/aipr","titre":"Formations AIPR","description":"SECURIFORM prépare aux 3 niveaux d'AIPR (Opérateur, Encadrant, Concepteur). Attestation valable 5 ans, conforme DT-DICT, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"AIPR DT-DICT reseaux"},
  {"href":"/vgp","titre":"Vérifications Générales Périodiques (VGP)","description":"SECURIFORM réalise les Vérifications Générales Périodiques (VGP) de vos équipements de levage et manutention, dans les Hauts-de-France.","categorie":"VGP","motsCles":"VGP verification generale periodique controle reglementaire"},
  {"href":"/blog","titre":"Blog : conseils et guides sur la sécurité au travail","description":"Conseils, actualités et guides pratiques sur la sécurité au travail, le CACES®, l'habilitation électrique et la prévention des risques.","categorie":"SECURIFORM","motsCles":"blog articles actualites"},
  {"href":"/formations-specifiques","titre":"Formations spécifiques","description":"SECURIFORM propose des formations sur mesure : tondeuses autoportées, tronçonneuses thermiques, balayeuses routières, gestes qui sauvent.","categorie":"Formation","motsCles":"sur mesure specifique"},
  {"href":"/gestes-postures","titre":"Formation gestes et postures","description":"SECURIFORM forme aux gestes et postures de manutention pour prévenir les TMS, conformément au Code du travail, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"TMS manutention dos ergonomie gestes postures"},
  {"href":"/outils","titre":"Outils","description":"Outils gratuits SECURIFORM : trouvez la formation sécurité adaptée à vos salariés, calculez la date de recyclage de vos formations, comparez les CACES® et listez vos VGP obligatoires.","categorie":"Outil","motsCles":"outils"},
  {"href":"/caces-R482B","titre":"CACES® R482B : Engins de chantier","description":"Formation CACES R482B avec SECURIFORM : catégories A à G, pelles, chargeuses, bouteurs, compacteurs, tombereaux. Certificat valable 10 ans.","categorie":"Formation","motsCles":"R482 engin de chantier pelle mini-pelle chargeuse bouteur compacteur tombereau tracteur BTP terrassement"},
  {"href":"/caces-R484A","titre":"CACES® R484A : Ponts roulants et portiques","description":"Formation CACES R484A avec SECURIFORM : commande au sol, techniques d'élingage, calcul de charge. Certificat valable 5 ans.","categorie":"Formation","motsCles":"R484 pont roulant portique levage elingage"},
  {"href":"/caces-R485A","titre":"CACES® R485A : Gerbeurs à conducteur accompagnant","description":"Formation CACES R485A avec SECURIFORM : conduite de gerbeurs à conducteur accompagnant, catégories 1 et 2. Certificat valable 5 ans, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"R485 gerbeur accompagnant transpalette"},
  {"href":"/caces-R486B","titre":"CACES® R486B : Nacelles élévatrices","description":"Formation CACES R486B avec SECURIFORM, groupes A et B : nacelles élévatrices ciseaux, plateformes sur mât, nacelles élévatrices à bras articulé ou télescopique. Certificat valable 5 ans.","categorie":"Formation","motsCles":"R486 nacelle élévatrice PEMP plateforme elevatrice ciseaux mat bras articule telescopique"},
  {"href":"/caces-R489A","titre":"CACES® R489A : Chariots de manutention","description":"Formation CACES R489A avec SECURIFORM : catégories 1A à 7, transpalettes, gerbeurs, chariots en porte-à-faux et à mât rétractable. 5 ans.","categorie":"Formation","motsCles":"R489 chariot elevateur cariste transpalette gerbeur porte-a-faux mat retractable manutention entrepot logistique"},
  {"href":"/caces-R490A","titre":"CACES® R490A : Grues auxiliaires de chargement","description":"Formation CACES R490A avec SECURIFORM : grues auxiliaires de chargement, option télécommande. Certificat valable 5 ans.","categorie":"Formation","motsCles":"R490 grue auxiliaire grue de chargement camion"},
  {"href":"/habilitation-electricien","titre":"Formation personnel électricien","description":"Formation SECURIFORM pour personnel électricien : basse et haute tension, véhicules électriques. Consignation en 5 étapes, recyclage 3 ans.","categorie":"Formation","motsCles":"electricien B1 B2 BR BC H1 H2 consignation haute tension basse tension"},
  {"href":"/habilitation-non-electricien","titre":"Formation personnel non-électricien","description":"Formation SECURIFORM pour personnel non-électricien : H0B0, BS, BE/HE Manœuvre, B0L véhicules électriques. Recyclage tous les 3 ans.","categorie":"Formation","motsCles":"H0B0 B0 H0 BS BE manoeuvre non electricien vehicule electrique B0L"},
  {"href":"/sst-initiale","titre":"Formation initiale SST","description":"Formation initiale SST avec SECURIFORM : cadre légal, programme en 10 modules, évaluation. 14h sur 2 jours, certificat valable 24 mois.","categorie":"Formation","motsCles":"SST sauveteur secouriste du travail premiers secours initiale"},
  {"href":"/sst-mac","titre":"MAC SST : Recyclage Sauveteur Secouriste du Travail","description":"Recyclage MAC SST avec SECURIFORM : 7h pour maintenir vos compétences, tous les 24 mois avant expiration du certificat.","categorie":"Formation","motsCles":"MAC SST recyclage maintien actualisation competences"},
  {"href":"/evacuation","titre":"Formation évacuation","description":"Formation SECURIFORM à l'évacuation : rôles de guide-file et serre-file, comportement en situation de danger, exercices tous les 6 mois.","categorie":"Formation","motsCles":"evacuation guide-file serre-file exercice incendie"},
  {"href":"/manipulation-extincteurs","titre":"Formation manipulation des extincteurs","description":"Formation SECURIFORM à la manipulation des extincteurs : triangle du feu, classes A à F, pratique sur feu réel.","categorie":"Formation","motsCles":"extincteur feu incendie"},
  {"href":"/equipier-premiere-intervention","titre":"Formation Équipier de Première Intervention","description":"Formation SECURIFORM Équipier de Première Intervention : obligations légales, organisation, RIA, coupures d'énergie. Référentiel APSAD R6.","categorie":"Formation","motsCles":"EPI equipier premiere intervention RIA incendie"},
  {"href":"/echafaudages-fixes","titre":"Formation échafaudages fixes (R408)","description":"Formation SECURIFORM aux échafaudages fixes R408 : montage/démontage, règles de stabilité, classes de charge, vérifications réglementaires.","categorie":"Formation","motsCles":"R408 echafaudage fixe montage"},
  {"href":"/echafaudages-roulants","titre":"Formation échafaudages roulants (R457)","description":"Formation SECURIFORM aux échafaudages roulants R457 : blocage des roues, stabilisateurs, procédure de déplacement sécurisé.","categorie":"Formation","motsCles":"R457 echafaudage roulant"},
  {"href":"/travaux-en-hauteur","titre":"Formation travaux en hauteur","description":"Formation SECURIFORM aux travaux en hauteur : hiérarchie des protections, harnais, points d'ancrage, longes, lignes de vie.","categorie":"Formation","motsCles":"harnais antichute ligne de vie hauteur"},
  {"href":"/aipr-concepteurs","titre":"Formation concepteurs AIPR","description":"Formation SECURIFORM concepteurs AIPR : Guichet Unique, investigations complémentaires, clauses DCE. Pour maîtres d'ouvrage et d'œuvre.","categorie":"Formation","motsCles":"AIPR concepteur bureau d'etudes maitre d'ouvrage DT-DICT"},
  {"href":"/aipr-encadrants","titre":"Formation encadrants AIPR","description":"Formation SECURIFORM encadrants AIPR : procédures DT-DICT, marquage-piquetage, arrêt de chantier, examen QCM. Attestation valable 5 ans.","categorie":"Formation","motsCles":"AIPR encadrant chef de chantier DT-DICT"},
  {"href":"/aipr-operateurs","titre":"Formation opérateurs AIPR","description":"Formation SECURIFORM opérateurs AIPR : classes de précision DT-DICT, distances de sécurité, règle du mètre et règle des 4A.","categorie":"Formation","motsCles":"AIPR operateur DT-DICT reseaux"},
  {"href":"/vgp-accessoires-levage","titre":"Vérifications Générales Périodiques des accessoires de levage","description":"VGP des accessoires de levage avec SECURIFORM : élingues, manilles, crochets, palonniers. Fréquence de 6 mois, directive Machines.","categorie":"VGP","motsCles":"VGP verification controle accessoires de levage"},
  {"href":"/vgp-bras-de-levage","titre":"Vérifications Générales Périodiques des bras de levage","description":"VGP des bras de levage avec SECURIFORM : systèmes hydrauliques, câbles, composants mécaniques. Fréquence de 6 mois.","categorie":"VGP","motsCles":"VGP verification controle bras de levage"},
  {"href":"/vgp-chargeuses","titre":"Vérifications Générales Périodiques des chargeuses","description":"VGP des chargeuses avec SECURIFORM : équipements concernés, éléments contrôlés, registre de sécurité. Fréquence de 6 mois.","categorie":"VGP","motsCles":"VGP verification controle chargeuses"},
  {"href":"/vgp-chariots-elevateurs","titre":"Vérifications Générales Périodiques des chariots élévateurs","description":"VGP des chariots élévateurs avec SECURIFORM : éléments contrôlés, registre de sécurité. Fréquence de 6 mois, Code du travail.","categorie":"VGP","motsCles":"VGP verification controle chariots élévateurs"},
  {"href":"/vgp-chariots-telescopiques","titre":"Vérifications Générales Périodiques des chariots télescopiques","description":"VGP des chariots télescopiques avec SECURIFORM : systèmes hydrauliques, structure, dispositifs de sécurité. Fréquence de 6 mois.","categorie":"VGP","motsCles":"VGP verification controle chariots télescopiques"},
  {"href":"/vgp-compacteurs","titre":"Vérifications Générales Périodiques des compacteurs","description":"VGP des compacteurs avec SECURIFORM : système de compression, rouleaux, parties mécaniques. Fréquence de 12 mois.","categorie":"VGP","motsCles":"VGP verification controle compacteurs"},
  {"href":"/vgp-grues-auxiliaires","titre":"Vérifications Générales Périodiques des grues auxiliaires","description":"VGP des grues auxiliaires avec SECURIFORM : équipements concernés, registre de sécurité. Fréquence de 6 mois.","categorie":"VGP","motsCles":"VGP verification controle grues auxiliaires"},
  {"href":"/vgp-hayons-elevateurs","titre":"Vérifications Générales Périodiques des hayons élévateurs","description":"VGP des hayons élévateurs avec SECURIFORM : fixation au châssis, bras de levage, vérins hydrauliques. Fréquence de 6 mois.","categorie":"VGP","motsCles":"VGP verification controle hayons élévateurs"},
  {"href":"/vgp-nacelles-elevatrices","titre":"Vérifications Générales Périodiques des nacelles élévatrices","description":"VGP des nacelles élévatrices (PEMP) avec SECURIFORM : inspection visuelle et essais de fonctionnement. Fréquence de 6 mois.","categorie":"VGP","motsCles":"VGP verification controle nacelles élévatrices"},
  {"href":"/vgp-pelleteuses","titre":"Vérifications Générales Périodiques des pelleteuses","description":"VGP des pelleteuses avec SECURIFORM : détection d'usure, fissures et déformations. Fréquence de 12 mois.","categorie":"VGP","motsCles":"VGP verification controle pelleteuses"},
  {"href":"/vgp-ponts-roulants","titre":"Vérifications Générales Périodiques des ponts roulants","description":"VGP des ponts roulants avec SECURIFORM : équipements concernés, registre de sécurité. Fréquence de 12 mois.","categorie":"VGP","motsCles":"VGP verification controle ponts roulants"},
  {"href":"/vgp-tombereaux","titre":"Vérifications Générales Périodiques des tombereaux","description":"VGP des tombereaux avec SECURIFORM : châssis, freinage, direction, mécanismes de déversement. Fréquence de 6 ou 12 mois.","categorie":"VGP","motsCles":"VGP verification controle tombereaux"},
  {"href":"/tondeuses-autoportees","titre":"Conduite en sécurité de tondeuses autoportées","description":"Formation SECURIFORM à la conduite des tondeuses autoportées : risques de retournement, vérifications, règles de conduite.","categorie":"Formation","motsCles":"tondeuse autoportee espaces verts"},
  {"href":"/tronconneuse-thermique","titre":"Utilisation en sécurité d'une tronçonneuse thermique","description":"Formation SECURIFORM à l'utilisation sécurisée d'une tronçonneuse thermique : risque de rebond, équipements de protection, vérifications.","categorie":"Formation","motsCles":"tronconneuse elagage abattage"},
  {"href":"/balayeuses-routieres","titre":"Conduite en sécurité de balayeuses routières","description":"Formation SECURIFORM à la conduite des balayeuses routières : angles morts, signalisation et vérifications avant utilisation, sur toute la moitié nord de la France.","categorie":"Formation","motsCles":"balayeuse voirie"},
  {"href":"/gestes-qui-sauvent","titre":"Sensibilisation aux gestes qui sauvent","description":"Sensibilisation SECURIFORM aux gestes qui sauvent : accessible à tous, sans prérequis, en quelques heures. Alerter les secours, gestes essentiels.","categorie":"Formation","motsCles":"premiers secours sensibilisation alerter massage cardiaque"},
  {"href":"/poids-de-test-vgp","titre":"Poids de test VGP","description":"VGP obligatoire : utilisez des blocs béton de masse certifiée pour tester la capacité de charge de vos engins de levage.","categorie":"VGP","motsCles":"poids de test epreuve charge VGP"},
  {"href":"/statistiques","titre":"Avis clients et rapports d'activité","description":"Consultez les avis clients et les rapports d'activité de SECURIFORM, organisme de formation certifié Qualiopi, année par année depuis 2019.","categorie":"SECURIFORM","motsCles":"statistiques avis taux de reussite satisfaction"},
  {"href":"/lentreprise","titre":"L'entreprise","description":"SECURIFORM est un organisme de formation à la sécurité au travail, certifié Qualiopi depuis 2021, présent sur toute la moitié nord de la France.","categorie":"SECURIFORM","motsCles":"entreprise qui sommes-nous qualiopi zone d'intervention"},
  {"href":"/nous-contacter","titre":"Nous contacter","description":"Contactez SECURIFORM, organisme de formation à Villeneuve d'Ascq (59650) : devis, renseignements, service client. 03 20 67 34 90.","categorie":"SECURIFORM","motsCles":"contact devis telephone adresse"},
  {"href":"/nous-recrutons","titre":"Nous recrutons","description":"SECURIFORM recrute des formateurs certifiés en sécurité au travail sur toute la moitié nord de la France. Rejoignez notre équipe.","categorie":"SECURIFORM","motsCles":"recrutement emploi formateur candidature"},
  {"href":"/outils/calculateur-recyclage","titre":"Calculateur de recyclage","description":"Calculez la date d'échéance de vos formations sécurité (CACES®, SST, habilitation électrique, AIPR…) et recevez un rappel par email avant leur expiration.","categorie":"Outil","motsCles":"calculateur recyclage echeance validite rappel"},
  {"href":"/outils/quelle-formation","titre":"Quelle formation me faut-il ?","description":"Répondez à quelques questions et découvrez la formation sécurité adaptée à vos salariés : CACES®, habilitation électrique, SST, incendie, travaux en hauteur, AIPR.","categorie":"Outil","motsCles":"questionnaire choisir formation"},
  {"href":"/mentions-legales","titre":"Mentions légales","description":"Mentions légales du site SECURIFORM : éditeur, hébergeur, propriété intellectuelle, données personnelles et cookies.","categorie":"Informations","motsCles":"mentions legales"},
  {"href":"/conditions-generales-de-vente","titre":"Conditions générales de vente","description":"Conditions générales de vente SECURIFORM : formations inter/intra-entreprise, facturation, annulation, responsabilité, protection des données.","categorie":"Informations","motsCles":"CGV conditions generales de vente"},
  {"href":"/politique-de-confidentialite","titre":"Politique de confidentialité","description":"Politique de confidentialité SECURIFORM : données collectées, finalités, durées de conservation, sous-traitants et droits RGPD.","categorie":"Informations","motsCles":"confidentialite RGPD donnees personnelles"},
  {"href":"/politique-cookies","titre":"Politique de cookies","description":"Liste des cookies et traceurs utilisés par le site SECURIFORM (nom, émetteur, finalité, durée) et gestion du consentement.","categorie":"Informations","motsCles":"cookies traceurs"},
  {"href":"/caces#comparateur","titre":"Comparateur de CACES®","description":"Les 6 CACES® côte à côte : engins concernés, durée de formation, recyclage et validité.","categorie":"Outil","motsCles":"comparer comparatif CACES duree validite"},
  {"href":"/vgp#checklist","titre":"Checklist réglementaire VGP","description":"Cochez vos équipements : vérifications obligatoires, fréquence et formations de vos conducteurs.","categorie":"Outil","motsCles":"checklist VGP frequence obligations equipements"},
];
