// Every public page of the site, shared by the sitemap and the chatbot's
// knowledge base so a new page only needs to be listed once.
export const hubs: { path: string; priority: number }[] = [
  { path: "/", priority: 1 },
  { path: "/caces", priority: 0.9 },
  { path: "/habilitation-electrique", priority: 0.9 },
  { path: "/secourisme", priority: 0.9 },
  { path: "/incendie-evacuation", priority: 0.9 },
  { path: "/travaux-hauteur-echafaudages", priority: 0.9 },
  { path: "/aipr", priority: 0.9 },
  { path: "/vgp", priority: 0.9 },
  { path: "/blog", priority: 0.8 },
  { path: "/formations-specifiques", priority: 0.8 },
  { path: "/gestes-postures", priority: 0.8 },
];

export const pages: string[] = [
  "/caces-R482B",
  "/caces-R484A",
  "/caces-R485A",
  "/caces-R486B",
  "/caces-R489A",
  "/caces-R490A",
  "/habilitation-electricien",
  "/habilitation-non-electricien",
  "/sst-initiale",
  "/sst-mac",
  "/evacuation",
  "/manipulation-extincteurs",
  "/equipier-premiere-intervention",
  "/echafaudages-fixes",
  "/echafaudages-roulants",
  "/travaux-en-hauteur",
  "/aipr-concepteurs",
  "/aipr-encadrants",
  "/aipr-operateurs",
  "/vgp-accessoires-levage",
  "/vgp-bras-de-levage",
  "/vgp-chargeuses",
  "/vgp-chariots-elevateurs",
  "/vgp-chariots-telescopiques",
  "/vgp-compacteurs",
  "/vgp-grues-auxiliaires",
  "/vgp-hayons-elevateurs",
  "/vgp-nacelles-elevatrices",
  "/vgp-pelleteuses",
  "/vgp-ponts-roulants",
  "/vgp-tombereaux",
  "/tondeuses-autoportees",
  "/tronconneuse-thermique",
  "/balayeuses-routieres",
  "/gestes-qui-sauvent",
  "/poids-de-test-vgp",
  "/statistiques",
  "/lentreprise",
  "/nous-contacter",
  "/nous-recrutons",
];

export const legal: string[] = ["/mentions-legales", "/conditions-generales-de-vente"];
